server:
  port: 8081

#spring:
#  application:
#    name: OAUTH-SERVICE
#  datasource:
#    url: jdbc:mysql://localhost:3306/dnc?useSSL=false
#    username: root
#    password:  
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#Google
#security:
#  oauth2:
#    client:
#      client-id: CLIENT_ID
#      client-secret: SECRET
#      access-token-uri: https://www.googleapis.com/oauth2/v3/token
#      user-authorization-uri: https://accounts.google.com/o/oauth2/auth
#      token-name: oauth_token
#      authentication-scheme: query
#      client-authentication-scheme: form
#      scope: profile email
#       
#    resource.user-info-uri: https://www.googleapis.com/userinfo/v2/me
#    resource.prefer-token-info: false

#Github    
#security:
#  oauth2:
#    client:
#      client-id: CLIENT_ID
#      client-secret: SECRET
#      access-token-uri: https://www.github.com/login/oauth/access_token
#      user-authorization-uri: https://www.github.com/login/oauth/authorize
#      authentication-scheme: query
#      client-authentication-scheme: form


#Facebook
security:
  oauth2:
    client:
      clientId: CLIENT_ID
      clientSecret: SECRET
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me